CREATE TABLE IF NOT EXISTS tasks(
   id serial PRIMARY KEY NOT NULL,
   name VARCHAR NOT NULL,
   description VARCHAR,
   end_date DATE,
   status VARCHAR, 
   priority INTEGER,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);